"""Export a trained BC checkpoint to a plain-JS weights module for the in-browser bot.

    python -m dicewars_bc.export_weights --ckpt checkpoints/bc_model.pt \
        --out ../src/ai/bcPolicyWeights.js

The in-browser bot runs the policy with a hand-written **synchronous** forward pass
(``src/ai/bcForward.js``) rather than ONNX Runtime Web, because the bot contract
``(BotState) -> {from,to}|null`` is synchronous everywhere in the arena while ORT's
``session.run`` is async. For this tiny per-edge MLP a pure-JS forward is trivially
fast, needs no WASM bundle, and keeps the sync contract. The ONNX export remains the
canonical numeric reference the JS forward is cross-checked against (see the
JS↔Python parity fixture/tests).

This writes a ``.js`` module (not ``.json``) so it imports identically in the Vite
browser bundle, the Node arena CLI (`node scripts/arena.mjs`), and Vitest — none of
which need JSON import attributes that way.

Two on-disk formats (``--packed`` / ``--no-packed``):

* **packed (default)** — the ~102k float weights are emitted as ONE base64-encoded
  little-endian ``Float32`` blob plus a compact shape descriptor, and the module is
  ``export const BC_POLICY = unpackPolicy({…})``. This is ~80% smaller than raw
  JSON-in-JS floats (issue #51: the eager bundle chunk no longer carries multi-MB of
  weight text) and is numerically lossless — the values are already float32, so the
  ``Float32Array`` round-trip recovers identical doubles. The generated module imports
  the sibling decoder ``src/ai/unpackPolicyWeights.js``, so a packed export MUST target
  a directory that has that decoder beside it (i.e. ``src/ai/``).
* **no-packed** — the legacy self-contained ``export const BC_POLICY = {…}`` JSON form,
  with each ``nn.Linear`` as ``{w, b, relu}``. It has no imports, so it loads from any
  directory — this is what PPO-league snapshots use (`snapshot_callback.py`), since
  those ``snap-*.weights.js`` files are written to a transient run dir, not ``src/ai/``.

Either way ``w`` is the PyTorch ``[out, in]`` weight, ``b`` the ``[out]`` bias, and
``relu`` whether a ReLU follows it in that MLP.

To re-emit an EXISTING weights module in a different format without the original
checkpoint (e.g. shrinking the shipped files), use ``--repack-js`` instead of ``--ckpt``::

    python -m dicewars_bc.export_weights --repack-js ../src/ai/bcPolicyWeights.js \
        --out ../src/ai/bcPolicyWeights.js   # repack in place → packed

The weights are bit-identical across a repack, so the sibling parity fixture stays valid
and is left untouched (``--fixture`` is rejected with ``--repack-js``).
"""

from __future__ import annotations

import argparse
import base64
import json
import re
from pathlib import Path

import numpy as np
import torch
from torch import nn

from .manifest import EXPECTED_ENCODING_VERSION
from .model import EdgePolicyNet, ModelConfig

# The five Sequential MLPs of EdgePolicyNet, mapped to camelCase keys the JS reads.
_HEADS = {
    "nodeEncoder": "node_encoder",
    "playerEncoder": "player_encoder",
    "context": "context",
    "edgeHead": "edge_head",
    "valueHead": "value_head",
}

# Fixed head order the packed float-blob is laid out in (and the JS decoder walks). Must
# match `_HEADS`' insertion order; named explicitly so the byte layout can't silently
# drift if `_HEADS` is ever reordered.
_HEAD_ORDER = list(_HEADS)

# The packed module imports its decoder from this sibling file (see src/ai/unpackPolicyWeights.js).
_DECODER_SIBLING = "unpackPolicyWeights.js"

_GEN_HEADER = (
    "// AUTO-GENERATED by ml/dicewars_bc/export_weights.py — do not edit by hand.\n"
    "// Weights for the in-browser behavioral-cloning bot (src/ai/ai_bc.js), run via\n"
    "// the synchronous pure-JS forward pass in src/ai/bcForward.js.\n"
)


def _dump_mlp(seq: nn.Sequential) -> list[dict]:
    """A Sequential of Linear/ReLU → a list of ``{w, b, relu}`` layers.

    ``relu`` marks whether the very next module in the Sequential is a ReLU, so the
    JS forward applies the exact same nonlinearity pattern (``_mlp`` puts a ReLU
    after every Linear except the last)."""
    children = list(seq.children())
    layers = []
    for i, mod in enumerate(children):
        if not isinstance(mod, nn.Linear):
            continue
        relu = i + 1 < len(children) and isinstance(children[i + 1], nn.ReLU)
        layers.append(
            {
                "w": mod.weight.detach().cpu().tolist(),  # [out, in]
                "b": mod.bias.detach().cpu().tolist(),  # [out]
                "relu": relu,
            }
        )
    return layers


def _count_params(payload: dict) -> int:
    """Trainable-param count of a materialized payload (sum of every Linear's W + b)."""
    n = 0
    for head in payload["layers"].values():
        for layer in head:
            out_dim = len(layer["w"])
            in_dim = len(layer["w"][0]) if out_dim else 0
            n += out_dim * in_dim + len(layer["b"])
    return n


def _pack_payload(payload: dict) -> dict:
    """Materialized payload → compact form: floats hoisted into one base64 blob.

    ``layers`` shrinks to a shape descriptor (``{head: [[out, in, relu], …]}``) and a
    new ``data`` key holds every ``w``/``b`` value as a base64 little-endian float32
    blob, laid out head-by-head in ``_HEAD_ORDER`` and, per layer, row-major ``w``
    ([out][in]) then ``b`` ([out]). ``src/ai/unpackPolicyWeights.js`` reverses this."""
    floats: list[float] = []
    shape: dict[str, list] = {}
    for head in _HEAD_ORDER:
        shape[head] = []
        for layer in payload["layers"][head]:
            w = layer["w"]
            b = layer["b"]
            out_dim = len(w)
            in_dim = len(w[0]) if out_dim else 0
            shape[head].append([out_dim, in_dim, bool(layer["relu"])])
            for row in w:
                floats.extend(row)
            floats.extend(b)
    blob = np.asarray(floats, dtype="<f4").tobytes()
    return {
        "encodingVersion": payload["encodingVersion"],
        "teacher": payload["teacher"],
        "selectionMetric": payload["selectionMetric"],
        "selectionAccuracy": payload["selectionAccuracy"],
        "config": payload["config"],
        "layers": shape,
        "data": base64.b64encode(blob).decode("ascii"),
    }


def _decode_packed(compact: dict) -> dict:
    """Compact form → materialized payload — the Python mirror of JS ``unpackPolicy``.

    Lets ``--repack-js`` round-trip an already-packed module, and lets the export test
    cross-check the packer's byte layout without going through JS."""
    f32 = np.frombuffer(base64.b64decode(compact["data"]), dtype="<f4")
    off = 0
    layers: dict[str, list] = {}
    for head, head_shape in compact["layers"].items():
        layers[head] = []
        for out_dim, in_dim, relu in head_shape:
            n_w = out_dim * in_dim
            w = f32[off : off + n_w].reshape(out_dim, in_dim).tolist()
            off += n_w
            b = f32[off : off + out_dim].tolist()
            off += out_dim
            layers[head].append({"w": w, "b": b, "relu": bool(relu)})
    if off != f32.size:
        raise ValueError(f"packed shape describes {off} floats but blob holds {f32.size}")
    meta = {k: v for k, v in compact.items() if k not in ("data", "layers")}
    return {**meta, "layers": layers}


def _emit_js(payload: dict, out_path: str | Path, *, packed: bool) -> Path:
    """Write a materialized payload to a JS weights module in the chosen format."""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    n_params = _count_params(payload)
    header = (
        _GEN_HEADER
        + f"// teacher={payload['teacher']} · {n_params} params · "
        + f"selection={payload['selectionMetric']}={payload['selectionAccuracy']}\n"
        + "/* eslint-disable */\n"
    )
    if packed:
        decoder = out_path.parent / _DECODER_SIBLING
        if not decoder.exists():
            raise FileNotFoundError(
                f"packed export needs {_DECODER_SIBLING} beside the output ({decoder} not found). "
                "Export into src/ai/ (where the decoder lives), or pass --no-packed for a "
                "self-contained JSON module (e.g. PPO-league snapshots written to a temp dir)."
            )
        compact = _pack_payload(payload)
        body = json.dumps(compact, separators=(",", ":"))
        text = (
            header
            + f"import {{ unpackPolicy }} from './{_DECODER_SIBLING}';\n"
            + f"export const BC_POLICY = unpackPolicy({body});\n"
        )
    else:
        body = json.dumps(payload, separators=(",", ":"))
        text = header + f"export const BC_POLICY = {body};\n"
    out_path.write_text(text)
    print(
        f"Wrote JS weights → {out_path}  ({n_params:,} params, {out_path.stat().st_size:,} bytes)"
    )
    return out_path


def _read_js_payload(js_text: str) -> dict:
    """Extract a materialized payload from a generated weights module (either format)."""
    m = re.search(r"export const BC_POLICY = unpackPolicy\((\{.*\})\);", js_text, re.DOTALL)
    if m:
        return _decode_packed(json.loads(m.group(1)))
    m = re.search(r"export const BC_POLICY = (\{.*\});", js_text, re.DOTALL)
    if m:
        return json.loads(m.group(1))
    raise ValueError("no `export const BC_POLICY = …` found in the input JS module")


def _make_fixture(
    model: EdgePolicyNet, config: ModelConfig, n_cases: int = 6, seed: int = 0
) -> dict:
    """Reference (input → logits/value) cases the JS forward is cross-checked against.

    Random but structurally valid single steps (present-mask, in-range ids, a trailing
    STOP edge), run through the *same* loaded model — so the fixture is always
    consistent with the weights emitted alongside it. The JS parity test replays each
    case through ``bcForward.js`` and asserts it reproduces these logits."""
    g = torch.Generator().manual_seed(seed)
    a = config.max_areas
    cases = []
    for _ in range(n_cases):
        p = int(torch.randint(2, 8, (1,), generator=g).item())
        n_attacks = int(torch.randint(0, 6, (1,), generator=g).item())
        e = n_attacks + 1  # + trailing STOP

        nodes = torch.rand(1, a, config.node_features, generator=g)
        nodes[0, :, EdgePolicyNet.PRESENT_COL] = (torch.rand(a, generator=g) > 0.3).float()
        nodes[0, 0, :] = 0.0  # sentinel id 0 absent
        players = torch.rand(1, p, config.player_features, generator=g)
        board = torch.rand(1, config.board_features, generator=g)

        edge_feat = torch.rand(e, config.edge_features, generator=g)
        edge_from = torch.randint(1, a, (e,), generator=g)
        edge_to = torch.randint(1, a, (e,), generator=g)
        edge_feat[-1] = 0.0  # STOP edge: zero all features ...
        edge_feat[-1, 3] = 1.0  # ... except isStop (col 3, width-agnostic across versions)
        edge_from[-1] = 0
        edge_to[-1] = 0
        edge_batch = torch.zeros(e, dtype=torch.int64)

        with torch.no_grad():
            logits, value = model(nodes, players, board, edge_feat, edge_from, edge_to, edge_batch)

        cases.append(
            {
                "nodes": nodes[0].tolist(),
                "players": players[0].tolist(),
                "board": board[0].tolist(),
                "edges": edge_feat.tolist(),
                "edgeIndex": torch.stack([edge_from, edge_to], dim=1).tolist(),
                "logits": logits.tolist(),
                "value": value[0].tolist(),
            }
        )
    return {"seed": seed, "cases": cases}


def _build_payload(model: EdgePolicyNet, config: ModelConfig, ckpt: dict) -> dict:
    """Provenance + dims + every MLP's {w,b,relu} → the materialized payload dict."""
    return {
        "encodingVersion": ckpt.get("encoding_version"),
        "teacher": ckpt.get("teacher"),
        "selectionMetric": ckpt.get("selection_metric"),
        "selectionAccuracy": ckpt.get("selection_accuracy"),
        # Dims the JS encoder/forward need. presentCol mirrors EdgePolicyNet.PRESENT_COL.
        "config": {
            "maxAreas": config.max_areas,
            "nodeFeatures": config.node_features,
            "playerFeatures": config.player_features,
            "boardFeatures": config.board_features,
            "edgeFeatures": config.edge_features,
            "nodeHidden": config.node_hidden,
            "playerHidden": config.player_hidden,
            "contextHidden": config.context_hidden,
            "edgeHidden": config.edge_hidden,
            "presentCol": EdgePolicyNet.PRESENT_COL,
        },
        "layers": {js_key: _dump_mlp(getattr(model, attr)) for js_key, attr in _HEADS.items()},
    }


def export(
    ckpt_path: str | Path,
    out_path: str | Path,
    fixture_path: str | Path | None = None,
    *,
    packed: bool = True,
) -> Path:
    # weights_only=True: BC/repacked-PPO checkpoints are tensors + a plain
    # dict/str/num payload (same contract load_bc_checkpoint loads), so this avoids the
    # arbitrary-code unpickler and stays consistent with the rest of the pipeline.
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=True)

    # Fail fast on an encoding-version skew: the JS encoder/forward only support the
    # current version, and makeBC rejects a mismatch at load — catch it here so a stale
    # checkpoint never produces a silently-wrong weights module.
    ev = ckpt.get("encoding_version")
    if ev != EXPECTED_ENCODING_VERSION:
        raise ValueError(
            f"checkpoint encoding_version={ev!r} != {EXPECTED_ENCODING_VERSION} ({ckpt_path}); "
            "re-export from a checkpoint matching the current JS encoding "
            "(src/arena/encodeObservation.js / dicewars_bc.manifest)."
        )

    config = ModelConfig(**ckpt["config"])
    model = EdgePolicyNet(config)
    model.load_state_dict(ckpt["state_dict"])
    model.eval()

    payload = _build_payload(model, config, ckpt)
    out_path = _emit_js(payload, out_path, packed=packed)

    if fixture_path is not None:
        fixture = {"config": payload["config"], **_make_fixture(model, config)}
        fixture_path = Path(fixture_path)
        fixture_path.parent.mkdir(parents=True, exist_ok=True)
        fixture_path.write_text(json.dumps(fixture, indent=2) + "\n")
        print(f"Wrote JS↔Python parity fixture → {fixture_path}  ({len(fixture['cases'])} cases)")

    return out_path


def repack_js(in_path: str | Path, out_path: str | Path, *, packed: bool = True) -> Path:
    """Re-emit an existing weights module in the chosen format — no checkpoint needed.

    Reads the materialized weights back out of a generated module (either format) and
    writes them again. The float values are bit-identical across the round-trip, so any
    sibling parity fixture stays valid and is intentionally left untouched."""
    payload = _read_js_payload(Path(in_path).read_text())
    return _emit_js(payload, out_path, packed=packed)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Export a BC checkpoint to a JS weights module")
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument("--ckpt", help="Trained checkpoint (.pt from train.py)")
    src.add_argument(
        "--repack-js",
        dest="repack_js",
        help="Existing JS weights module to re-emit in a new format (no checkpoint needed)",
    )
    p.add_argument("--out", default="../src/ai/bcPolicyWeights.js", help="Output .js path")
    p.add_argument(
        "--fixture",
        default=None,
        help="Also write a JS↔Python parity fixture (reference logits) to this JSON path",
    )
    fmt = p.add_mutually_exclusive_group()
    fmt.add_argument(
        "--packed",
        dest="packed",
        action="store_true",
        default=True,
        help="(default) compact base64-float32 module; imports ./unpackPolicyWeights.js",
    )
    fmt.add_argument(
        "--no-packed",
        dest="packed",
        action="store_false",
        help="self-contained JSON-in-JS module (loads from any dir; used for snapshots)",
    )
    return p


def main() -> None:
    args = build_parser().parse_args()
    if args.repack_js:
        if args.fixture:
            raise SystemExit(
                "--fixture is not supported with --repack-js: there is no model to sample, and "
                "the existing fixture stays valid for bit-identical repacked weights."
            )
        repack_js(args.repack_js, args.out, packed=args.packed)
    else:
        export(args.ckpt, args.out, fixture_path=args.fixture, packed=args.packed)


if __name__ == "__main__":
    main()
