/**
 * JS↔Python parity for the behavioral-cloning forward pass.
 *
 * The browser bot runs the policy with the hand-written synchronous forward in
 * `src/ai/bcForward.js`. This asserts that forward reproduces the PyTorch model's
 * logits/value on a fixture of reference cases generated by
 * `ml/dicewars_bc/export_weights.py --fixture` from the SAME checkpoint that
 * produced `src/ai/bcPolicyWeights.js` (so weights and fixture stay consistent —
 * regenerate both together when the model changes). PyTorch computes in float32 and
 * JS in doubles, so logits are compared with a small absolute tolerance; the
 * argmax (the actually-chosen action) must match exactly.
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { argmax, forward } from '../../src/ai/bcForward.js';
import { BC_POLICY } from '../../src/ai/bcPolicyWeights.js';
import {
  BOARD_FEATURES,
  EDGE_FEATURES,
  NODE_FEATURES,
  PLAYER_FEATURES,
} from '../../src/arena/encodeObservation.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(readFileSync(resolve(here, '../fixtures/bc/forwardCases.json'), 'utf8'));

const TOL = 2e-3; // float32 (torch) vs double (JS) accumulation slack

describe('bcForward — JS↔Python parity', () => {
  it('has cases to check', () => {
    expect(fixture.cases.length).toBeGreaterThan(0);
  });

  fixture.cases.forEach((c, idx) => {
    it(`reproduces PyTorch logits + value for case ${idx} (${c.edges.length} edges)`, () => {
      const { logits, value } = forward(BC_POLICY, {
        nodes: c.nodes,
        players: c.players,
        board: c.board,
        edges: c.edges,
        edgeIndex: c.edgeIndex,
      });

      expect(logits.length).toBe(c.logits.length);
      const maxLogitErr = Math.max(...logits.map((v, i) => Math.abs(v - c.logits[i])));
      expect(maxLogitErr).toBeLessThan(TOL);

      const maxValueErr = Math.max(...value.map((v, i) => Math.abs(v - c.value[i])));
      expect(maxValueErr).toBeLessThan(TOL);

      // The practical invariant: the JS net picks the same action as PyTorch.
      expect(argmax(logits)).toBe(argmax(c.logits));
    });
  });
});

describe('bcForward — v2 slice-down compat (the [D-31] append-only contract)', () => {
  /*
   * The live encoder emits v3-width rows; the shipped v2 policy must read them as
   * if the appended tail columns did not exist. This is structural in forward():
   * linear() iterates the WEIGHT's input dim, and every concat keeps the
   * variable-width tensor last — so padding each row out to the v3 widths with
   * garbage must leave logits and value BIT-IDENTICAL. If someone reorders a
   * concat or inserts (rather than appends) a column, this test screams.
   */
  const padRow = (row, width, fill) => [...row, ...new Array(width - row.length).fill(fill)];

  fixture.cases.forEach((c, idx) => {
    it(`v2 policy ignores appended v3 columns (case ${idx})`, () => {
      const base = forward(BC_POLICY, {
        nodes: c.nodes,
        players: c.players,
        board: c.board,
        edges: c.edges,
        edgeIndex: c.edgeIndex,
      });
      // 0.7 (not 0) so a tail column that IS read would visibly change the result.
      const padded = forward(BC_POLICY, {
        nodes: c.nodes.map(r => padRow(r, NODE_FEATURES.length, 0.7)),
        players: c.players.map(r => padRow(r, PLAYER_FEATURES.length, 0.7)),
        board: padRow(c.board, BOARD_FEATURES.length, 0.7),
        edges: c.edges.map(r => padRow(r, EDGE_FEATURES.length, 0.7)),
        edgeIndex: c.edgeIndex,
      });
      expect(padded.logits).toEqual(base.logits);
      expect(padded.value).toEqual(base.value);
    });
  });
});
